<?php
// database/seeders/ReferenceDataSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReferenceDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Incident Types
        DB::table('incident_types')->insert([
            [
                'name' => 'Rape',
                'icon' => '⚠️',
                'category' => 'sexual',
                'description' => 'Non-consensual sexual intercourse',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Defilement',
                'icon' => '⚠️',
                'category' => 'sexual',
                'description' => 'Sexual intercourse with a minor',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Physical Assault',
                'icon' => '👊',
                'category' => 'physical',
                'description' => 'Physical violence or battery',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emotional Abuse',
                'icon' => '😔',
                'category' => 'emotional',
                'description' => 'Psychological or emotional mistreatment',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Economic Abuse',
                'icon' => '💰',
                'category' => 'economic',
                'description' => 'Financial control or exploitation',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Child Marriage',
                'icon' => '👰',
                'category' => 'social',
                'description' => 'Marriage of a child under 18 years',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FGM',
                'icon' => '⚕️',
                'category' => 'social',
                'description' => 'Female Genital Mutilation',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cyberbullying',
                'icon' => '💻',
                'category' => 'digital',
                'description' => 'Online harassment or bullying',
                'is_active' => true,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stalking',
                'icon' => '👁️',
                'category' => 'other',
                'description' => 'Repeated unwanted attention or harassment',
                'is_active' => true,
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sexual Harassment',
                'icon' => '🛑',
                'category' => 'sexual',
                'description' => 'Unwelcome sexual behavior or advances',
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Other',
                'icon' => '📌',
                'category' => 'other',
                'description' => 'Other types of GBV incidents',
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 2. Priority Levels
        DB::table('priority_levels')->insert([
            [
                'name' => 'Low',
                'color' => 'success',
                'description' => 'Non-urgent, routine follow-up',
                'icon' => '📌',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Normal',
                'color' => 'primary',
                'description' => 'Standard handling time',
                'icon' => '✓',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'High',
                'color' => 'warning',
                'description' => 'Requires prompt attention',
                'icon' => '⚠️',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Critical',
                'color' => 'danger',
                'description' => 'Immediate intervention needed',
                'icon' => '🚨',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 3. Confidentiality Levels
        DB::table('confidentiality_levels')->insert([
            [
                'name' => 'Standard',
                'description' => 'Accessible to all authorized case workers',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Restricted',
                'description' => 'Limited access to senior staff only',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anonymous',
                'description' => 'Survivor identity anonymized',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 4. ID Types
        DB::table('id_types')->insert([
            [
                'name' => 'National ID',
                'description' => 'National Identification Card',
                'requires_number' => true,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Passport',
                'description' => 'International Passport',
                'requires_number' => true,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Birth Certificate',
                'description' => 'Birth Certificate',
                'requires_number' => true,
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alien Card',
                'description' => 'Alien Identification Card',
                'requires_number' => true,
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Other',
                'description' => 'Other forms of identification',
                'requires_number' => false,
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 5. Disability Types
        DB::table('disability_types')->insert([
            [
                'name' => 'Physical Disability',
                'icon' => '🦽',
                'category' => 'mobility',
                'description' => 'Physical impairment affecting mobility',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Visual Impairment',
                'icon' => '👁️',
                'category' => 'sensory',
                'description' => 'Blindness or low vision',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hearing Impairment',
                'icon' => '👂',
                'category' => 'sensory',
                'description' => 'Deafness or hard of hearing',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Speech Impairment',
                'icon' => '🗣️',
                'category' => 'communication',
                'description' => 'Difficulty with speech or communication',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Intellectual Disability',
                'icon' => '🧠',
                'category' => 'cognitive',
                'description' => 'Cognitive or learning difficulties',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mental Health Condition',
                'icon' => '🧘',
                'category' => 'psychosocial',
                'description' => 'Mental health disorders or conditions',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Multiple Disabilities',
                'icon' => '🔄',
                'category' => 'multiple',
                'description' => 'Two or more types of disabilities',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Albinism',
                'icon' => '✨',
                'category' => 'other',
                'description' => 'Albinism condition',
                'is_active' => true,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Other Disability',
                'icon' => '📌',
                'category' => 'other',
                'description' => 'Other types of disabilities',
                'is_active' => true,
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 6. Age Ranges
        DB::table('age_ranges')->insert([
            [
                'name' => '0-16 years',
                'min_age' => 0,
                'max_age' => 16,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '17-35 years',
                'min_age' => 17,
                'max_age' => 35,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '36-60 years',
                'min_age' => 36,
                'max_age' => 60,
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '60+ years',
                'min_age' => 60,
                'max_age' => null,
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 7. Gender Options
        DB::table('gender_options')->insert([
            [
                'name' => 'Male',
                'icon' => '👨',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Female',
                'icon' => '👩',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Other',
                'icon' => '👤',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 8. Relationship Options
        DB::table('relationship_options')->insert([
            [
                'name' => 'Spouse/Partner',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Family Member',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Neighbour',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colleague',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stranger',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Authority Figure',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Other',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 9. Case Status Options
        DB::table('case_status_options')->insert([
            [
                'name' => 'Reported',
                'color' => 'info',
                'icon' => '🚨',
                'description' => 'Case has been reported',
                'is_active' => true,
                'is_concluded' => false,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Under Investigation',
                'color' => 'warning',
                'icon' => '⚠️',
                'description' => 'Case is under active investigation',
                'is_active' => true,
                'is_concluded' => false,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Medical Attention',
                'color' => 'primary',
                'icon' => '🏥',
                'description' => 'Receiving medical care',
                'is_active' => true,
                'is_concluded' => false,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Legal Proceedings',
                'color' => 'danger',
                'icon' => '⚖️',
                'description' => 'Case in legal process',
                'is_active' => true,
                'is_concluded' => false,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Counselling',
                'color' => 'info',
                'icon' => '💬',
                'description' => 'Receiving psychosocial support',
                'is_active' => true,
                'is_concluded' => false,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shelter Provided',
                'color' => 'success',
                'icon' => '🏠',
                'description' => 'Survivor in safe shelter',
                'is_active' => true,
                'is_concluded' => false,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 10. Conclusion Types
        DB::table('conclusion_types')->insert([
            [
                'name' => 'Successful Prosecution',
                'icon' => '⚖️',
                'color' => 'success',
                'description' => 'Perpetrator successfully prosecuted',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Out of Court Settlement',
                'icon' => '🤝',
                'color' => 'info',
                'description' => 'Settled outside court',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Referred to Other Agency',
                'icon' => '🔄',
                'color' => 'primary',
                'description' => 'Case referred to another organization',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Survivor Declined Further Action',
                'icon' => '🚫',
                'color' => 'warning',
                'description' => 'Survivor chose not to proceed',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Insufficient Evidence',
                'icon' => '📋',
                'color' => 'danger',
                'description' => 'Case closed due to lack of evidence',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Survivor Relocated',
                'icon' => '🏠',
                'color' => 'secondary',
                'description' => 'Survivor relocated for safety',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Other',
                'icon' => '📌',
                'color' => 'secondary',
                'description' => 'Other conclusion types',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 11. Referral Types
        DB::table('referral_types')->insert([
            [
                'name' => 'Medical Attention',
                'icon' => '🏥',
                'color' => 'danger',
                'description' => 'Referral to medical services',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Legal Proceedings',
                'icon' => '⚖️',
                'color' => 'primary',
                'description' => 'Referral to legal aid',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Psychosocial Support',
                'icon' => '💬',
                'color' => 'info',
                'description' => 'Referral to counseling services',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shelter Provided',
                'icon' => '🏠',
                'color' => 'success',
                'description' => 'Referral to safe housing',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Economic Empowerment',
                'icon' => '💰',
                'color' => 'warning',
                'description' => 'Referral to economic support programs',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Other',
                'icon' => '📌',
                'color' => 'secondary',
                'description' => 'Other referral services',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 12. Urgency Options
        DB::table('urgency_options')->insert([
            [
                'name' => 'Low',
                'color' => 'secondary',
                'icon' => '📌',
                'description' => 'Non-urgent, routine follow-up',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Normal',
                'color' => 'primary',
                'icon' => '✓',
                'description' => 'Standard handling time',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'High',
                'color' => 'warning',
                'icon' => '⚠️',
                'description' => 'Requires prompt attention',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Critical',
                'color' => 'danger',
                'icon' => '🚨',
                'description' => 'Immediate intervention needed',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // 13. Timeline Event Types
        DB::table('timeline_event_types')->insert([
            [
                'name' => 'Case Created',
                'icon' => 'PlusCircle',
                'color' => 'success',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Status Changed',
                'icon' => 'RefreshCw',
                'color' => 'info',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Case Concluded',
                'icon' => 'CheckCircle',
                'color' => 'primary',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Note Added',
                'icon' => 'MessageSquare',
                'color' => 'secondary',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Referral Made',
                'icon' => 'Share2',
                'color' => 'warning',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'File Uploaded',
                'icon' => 'FileText',
                'color' => 'dark',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}